# Generated by Django 3.2.5 on 2021-07-22 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_time',), 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
